"""S1 documentation & plasmid catalog generation (docx/xlsx), plus donor resolution."""

from __future__ import annotations

import json
import logging
import tempfile
import time
from collections.abc import Iterable, Mapping
from pathlib import Path
from typing import Any, Optional

import matplotlib.pyplot as plt
import pandas as pd
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord

try:
    from Bio import Entrez
except Exception:  # pragma: no cover
    Entrez = None

LOGGER = logging.getLogger(__name__)


def _s1():
    """
    Lazy import for S1 reporting to keep base imports light.
    Requires: python-docx, dna-features-viewer
    """
    try:
        from dna_features_viewer import CircularGraphicRecord, GraphicFeature
        from docx import Document
        from docx.shared import Inches
    except Exception as e:
        raise ImportError(
            "S1 reporting requires extras: pip install 'assembly-designer[s1doc]' "
            "(python-docx, dna-features-viewer)."
        ) from e
    return Document, Inches, CircularGraphicRecord, GraphicFeature


def build_plasmid_catalog_docx(
    repo_path: str | Path,
    *,
    output_name: str = "Plasmid_Database.docx",
    figure_width: float = 5.0,
    image_inches: float = 2.5,
    skip_feature_types: Optional[Iterable[str]] = None,
    render_maps: bool = True,
    filename_glob: Optional[str] = None,
    max_maps: Optional[int] = None,
) -> Path:
    """
    Create a DOCX catalog of plasmids from GenBank files.

    For each `.gb` / `.gbk` in `repo_path`, this function:
      1) (optionally) draws a circular plasmid map with `dna_features_viewer`,
      2) embeds the PNG into a Word document,
      3) writes the full DNA sequence,
      4) lists CDS sequences (+ translated protein) or, if no CDS exists,
         `misc_feature` DNA segments.

    Images are created in a temporary directory and not kept. The final DOCX is
    saved to the **current working directory** (where your notebook runs).

    Parameters
    ----------
    repo_path : str | Path
        Folder containing GenBank files (`.gb`, `.gbk`).
    output_name : str, default "Plasmid_Database.docx"
        Filename for the generated DOCX in the current working directory.
    figure_width : float, default 5.0
        Width (inches) for the circular plot generated by dna_features_viewer.
    image_inches : float, default 2.5
        Display width (inches) for embedded PNGs in the DOCX.
    skip_feature_types : Iterable[str] or None, optional
        Feature types to skip completely (case-insensitive).
        Defaults to `{"source", "homology"}`.
    render_maps : bool, default True
        If ``False``, do not render or embed plasmid maps (DOCX still contains
        sequences and feature text).
    filename_glob : str or None, optional
        Glob to restrict **which** files get a map (e.g. `"*TU1*.gb*"`).
        Ignored if `render_maps=False`.
    max_maps : int or None, optional
        Maximum number of maps to render/insert across the whole document.
        Ignored if `render_maps=False`.

    Returns
    -------
    Path
        Absolute path to the generated DOCX file.

    Raises
    ------
    FileNotFoundError
        If `repo_path` does not exist or is not a directory.

    Notes
    -----
    Dependencies:
      - biopython
      - python-docx
      - dna-features-viewer (only needed when `render_maps=True`)

    Examples
    --------
    >>> # No maps at all (just sequences & feature text):
    >>> build_plasmid_catalog("../reports/Assembly", render_maps=False)
    >>> # Only plot TU1 files, limit to 10 maps:
    >>> build_plasmid_catalog("../reports/Assembly", filename_glob="*TU1*.gb*", max_maps=10)
    """
    # Lazy S1-Imports (docx + features viewer)
    Document, Inches, CircularGraphicRecord, GraphicFeature = _s1()  # noqa: N806

    # local import for Glob-Matching (avoids Top-Level-Changes)
    import fnmatch as _fnmatch

    src_dir = Path(repo_path)
    if not src_dir.is_dir():
        raise FileNotFoundError(f"Folder not found: {src_dir}")

    skip = {s.lower() for s in (skip_feature_types or {"source", "homology"})}
    gb_files = sorted(
        [p for p in src_dir.iterdir() if p.suffix.lower() in {".gb", ".gbk"}]
    )
    if not gb_files:
        LOGGER.warning("No GenBank files (*.gb, *.gbk) found in %s", src_dir)

    out_path = Path.cwd() / output_name
    doc = Document()
    doc.add_heading("Plasmid Catalog", level=1)

    maps_done = 0
    with tempfile.TemporaryDirectory() as tmpdir:
        tmpdir_path = Path(tmpdir)

        for gb_path in gb_files:
            try:
                record = SeqIO.read(str(gb_path), "genbank")
            except Exception as exc:  # noqa: BLE001
                LOGGER.warning("Skipping %s (read error): %s", gb_path.name, exc)
                continue

            dna_sequence = str(record.seq)
            features: list[Any] = []  # GraphicFeature, resolved lazily via _s1()
            cds_sequences: list[str] = []
            found_cds = False

            # Build features + sequence lists
            for feature in getattr(record, "features", []):
                ftype_raw = str(getattr(feature, "type", ""))
                ftype = ftype_raw.lower()
                if ftype in skip:
                    continue

                qualifiers = getattr(feature, "qualifiers", {}) or {}
                label = (
                    (
                        qualifiers.get("label")
                        or qualifiers.get("gene")
                        or qualifiers.get("note")
                        or [ftype_raw]
                    )[0]
                    if isinstance(qualifiers, dict)
                    else ftype_raw
                )

                color_map = {
                    "promoter": "green",
                    "cds": "#ffd383",
                    "regulatory": "red",
                    "terminator": "purple",
                    "rbs": "blue",
                    "misc_binding": "blue",
                    "gene": "#ffd383",
                }
                color = color_map.get(ftype, "gray")

                try:
                    start = int(feature.location.start)
                    end = int(feature.location.end)
                    strand = getattr(feature.location, "strand", 0) or 0
                except Exception:  # noqa: BLE001
                    continue

                if end > start:
                    features.append(
                        GraphicFeature(
                            start=start,
                            end=end,
                            strand=strand,
                            color=color,
                            label=str(label),
                        )
                    )

                if ftype == "cds":
                    found_cds = True
                    try:
                        cds_seq = feature.extract(record.seq)
                        translation_list = qualifiers.get("translation", [])
                        if translation_list:
                            protein_seq = translation_list[0]
                        else:
                            protein_seq = str(Seq(str(cds_seq)).translate(to_stop=True))
                        cds_sequences.append(f"{label} (DNA): {cds_seq}")
                        cds_sequences.append(f"{label} (Protein): {protein_seq}")
                    except Exception as exc:  # noqa: BLE001
                        LOGGER.warning(
                            "CDS extraction failed in %s: %s", gb_path.name, exc
                        )

            if not found_cds:
                for feature in getattr(record, "features", []):
                    ftype = str(getattr(feature, "type", "")).lower()
                    if ftype == "misc_feature":
                        q = getattr(feature, "qualifiers", {}) or {}
                        label = (q.get("label") or q.get("note") or ["misc_feature"])[0]
                        try:
                            dna = feature.extract(record.seq)
                            cds_sequences.append(f"{label} (misc_feature-DNA): {dna}")
                        except Exception as exc:  # noqa: BLE001
                            LOGGER.warning(
                                "misc_feature extraction failed in %s: %s",
                                gb_path.name,
                                exc,
                            )

            # Decide whether to plot this file
            should_plot = bool(render_maps)
            if should_plot and filename_glob is not None:
                should_plot = _fnmatch.fnmatch(gb_path.name, filename_glob)
            if should_plot and max_maps is not None and maps_done >= max_maps:
                should_plot = False

            png_path: Optional[Path] = None
            if should_plot:
                try:
                    filtered = [f for f in features if f.end > f.start]
                    graphic_record = CircularGraphicRecord(
                        sequence_length=len(record.seq),
                        features=filtered,
                    )
                    ax, _ = graphic_record.plot(figure_width=figure_width)
                    png_path = tmpdir_path / (gb_path.stem + ".png")
                    # Direkt PNG speichern — kein SVG, kein cairosvg
                    ax.figure.savefig(png_path, bbox_inches="tight", dpi=300)
                    plt.close(ax.figure)
                    maps_done += 1
                except Exception as exc:  # noqa: BLE001
                    LOGGER.warning("Map rendering failed for %s: %s", gb_path.name, exc)
                    png_path = None

            # Write section
            doc.add_heading(f"Plasmid: {gb_path.name}", level=2)
            if png_path and png_path.exists():
                doc.add_picture(str(png_path), width=Inches(image_inches))

            doc.add_heading("Plasmid DNA sequence:", level=3)
            doc.add_paragraph(dna_sequence)

            if cds_sequences:
                doc.add_heading("CDS or misc_feature sequences:", level=3)
                for cds in cds_sequences:
                    doc.add_paragraph(str(cds))

    doc.save(out_path)
    LOGGER.info("DOCX written: %s", out_path)
    return out_path


_MISSING_TOKENS: set[str] = {
    "",
    ".",
    "-",
    "na",
    "n/a",
    "none",
    "unknown",
    "unbekannt",
    "synthetic construct",
    "plasmid",
}


def _clean_text(val: object) -> Optional[str]:
    """Normalize a free-text field and treat placeholders as missing.

    Parameters
    ----------
    val : object
        Any value that can be stringified.

    Returns
    -------
    str or None
        Cleaned, non-empty string or ``None`` if the value matches a placeholder.
    """
    s = str(val).strip()
    return None if s.lower() in _MISSING_TOKENS else s


def _first_qualifier(q: Mapping[str, list[Any]], *keys: str) -> Optional[str]:
    """Return the first non-empty qualifier value among `keys`, if present.

    Parameters
    ----------
    q : Mapping[str, list[Any]]
        Feature qualifiers as produced by Biopython.
    *keys : str
        Candidate qualifier keys to try in order.

    Returns
    -------
    str or None
        First non-empty string value, or ``None`` if not found.
    """
    for key in keys:
        vals = q.get(key) or []
        if isinstance(vals, list) and vals:
            v = str(vals[0]).strip()
            if v:
                return v
    return None


def _donor_from_record(record: SeqRecord) -> Optional[str]:
    """Extract organism/donor from a GenBank record.

    Strategy
    --------
    1. `record.annotations["organism"]`
    2. `/source` feature qualifiers: `organism`, `label`, `note`

    Parameters
    ----------
    record : SeqRecord
        GenBank record.

    Returns
    -------
    str or None
        Cleaned organism string, or ``None`` if not available or a placeholder.
    """
    org = _clean_text(record.annotations.get("organism"))
    if org:
        return org

    for feat in getattr(record, "features", []):
        if str(getattr(feat, "type", "")).lower() == "source":
            q = getattr(feat, "qualifiers", {}) or {}
            cand = _clean_text(_first_qualifier(q, "organism", "label", "note"))
            if cand:
                return cand
    return None


def _parse_accession(record: SeqRecord) -> Optional[str]:
    """Try to extract a single accession usable for NCBI lookups.

    Parameters
    ----------
    record : SeqRecord
        GenBank record.

    Returns
    -------
    str or None
        Accession string if found; otherwise ``None``.
    """
    accs = record.annotations.get("accessions") or []
    if isinstance(accs, list) and accs:
        return str(accs[0])

    rec_id = str(getattr(record, "id", "")).strip()
    if rec_id and not any(ch in rec_id for ch in " |"):
        return rec_id

    for xref in getattr(record, "dbxrefs", []):
        if ":" in xref:
            _, right = xref.split(":", 1)
            right = right.strip()
            if right:
                return right
    return None


def _load_mapping_csv(csv_path: Path) -> dict[str, str]:
    """Load curated donor mappings from CSV.

    Expected columns (flexible)
    ---------------------------
    - ``stem`` (file stem without extension) → ``donor``
    - optional ``accession`` → ``donor``
    - optional ``gene`` → ``donor``

    Missing columns are ignored.

    Parameters
    ----------
    csv_path : Path
        Path to the CSV file.

    Returns
    -------
    dict[str, str]
        Flat mapping with composite keys (``"stem::..."``, ``"acc::..."``,
        ``"gene::..."``) to donor strings.

    Raises
    ------
    FileNotFoundError
        If the CSV file does not exist.
    """
    if not Path(csv_path).is_file():
        raise FileNotFoundError(f"Mapping CSV not found: {csv_path}")

    df = pd.read_csv(csv_path)
    mapping: dict[str, str] = {}

    if "stem" in df.columns and "donor" in df.columns:
        for stem, donor in zip(df["stem"], df["donor"], strict=False):
            if pd.notna(stem) and pd.notna(donor):
                mapping[f"stem::{str(stem).strip()}"] = str(donor).strip()

    if "accession" in df.columns and "donor" in df.columns:
        for acc, donor in zip(df["accession"], df["donor"], strict=False):
            if pd.notna(acc) and pd.notna(donor):
                mapping[f"acc::{str(acc).strip()}"] = str(donor).strip()

    if "gene" in df.columns and "donor" in df.columns:
        for gene, donor in zip(df["gene"], df["donor"], strict=False):
            if pd.notna(gene) and pd.notna(donor):
                mapping[f"gene::{str(gene).strip().lower()}"] = str(donor).strip()

    return mapping


def _mapping_lookup(
    mapping: Mapping[str, str],
    stem: str,
    gene: Optional[str],
    accession: Optional[str],
) -> Optional[str]:
    """Resolve donor from curated mapping using several keys.

    Resolution order
    ----------------
    ``accession`` → ``stem`` → ``gene``

    Parameters
    ----------
    mapping : Mapping[str, str]
        Mapping produced by :func:`_load_mapping_csv`.
    stem : str
        File stem (without extension).
    gene : str or None
        Gene name inferred from features (if any).
    accession : str or None
        Accession parsed from record.

    Returns
    -------
    str or None
        Donor string if found; otherwise ``None``.
    """
    if accession and f"acc::{accession}" in mapping:
        return mapping[f"acc::{accession}"]
    if f"stem::{stem}" in mapping:
        return mapping[f"stem::{stem}"]
    if gene and f"gene::{gene.lower()}" in mapping:
        return mapping[f"gene::{gene.lower()}"]
    return None


def _read_json(path: Path) -> dict[str, Any]:
    """Read JSON from file, returning an empty dict on failure.

    Parameters
    ----------
    path : Path
        JSON file path.

    Returns
    -------
    dict[str, Any]
        Parsed JSON dict or empty dict if reading/parsing fails.
    """
    try:
        return json.loads(Path(path).read_text(encoding="utf-8"))
    except Exception:  # pragma: no cover - tolerant cache reader
        return {}


def _write_json(path: Path, data: Mapping[str, Any]) -> None:
    """Write a mapping as pretty JSON, creating parent directories if needed.

    Parameters
    ----------
    path : Path
        Output JSON file path.
    data : Mapping[str, Any]
        JSON-serializable mapping to write.

    Returns
    -------
    None
    """
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def _ncbi_lookup_organism(  # noqa: PLR0913 - explicit keyword-only params are intentional
    accession: str,
    *,
    email: Optional[str],
    api_key: Optional[str],
    cache_path: Optional[Path],
    rate_limit_s: float = 0.35,
) -> Optional[str]:
    """Query NCBI (nuccore) for the organism of an accession.

    Parameters
    ----------
    accession : str
        Accession to query in the ``nuccore`` database.
    email : str or None
        Email required by NCBI; if ``None``, no query is performed.
    api_key : str or None
        Optional NCBI API key.
    cache_path : Path or None
        JSON cache file. If present and contains the accession, the cached
        value is returned.
    rate_limit_s : float, default 0.35
        Sleep time after a successful query (simple politeness/rate limit).

    Returns
    -------
    str or None
        Organism name if available; otherwise ``None``.

    Notes
    -----
    - Requires internet and ``Bio.Entrez``.
    - Safe no-op if ``Entrez`` is unavailable or ``email`` is ``None``.
    """
    if Entrez is None or not email:
        return None

    cache: dict[str, Any] = {}
    if cache_path:
        cache = _read_json(cache_path)
        if accession in cache:
            return str(cache[accession])

    Entrez.email = email
    if api_key:
        Entrez.api_key = api_key

    try:
        handle = Entrez.esummary(db="nuccore", id=accession, retmode="xml")
        summary = Entrez.read(handle)
        handle.close()
        organism: Optional[str] = None
        if summary and isinstance(summary, list) and "Organism" in summary[0]:
            organism = str(summary[0]["Organism"]).strip()

        if not organism:
            return None

        if cache_path:
            cache[accession] = organism
            _write_json(cache_path, cache)

        time.sleep(max(0.0, rate_limit_s))
        return organism
    except Exception:  # pragma: no cover - network variability
        return None


def resolve_donor(  # noqa: PLR0913 - explicit, clear surface
    record: SeqRecord,
    *,
    file_stem: str,
    mapping_csv: Optional[Path] = None,
    enable_ncbi_fallback: bool = False,
    ncbi_email: Optional[str] = None,
    ncbi_api_key: Optional[str] = None,
    ncbi_cache: Optional[Path] = None,
) -> Optional[str]:
    """Resolve donor/organism using a **clear, ordered strategy**.

    Order
    -----
    1. **Primary** — read from the GenBank record itself (``annotations['organism']``
       or ``/source`` feature). If present and not a placeholder → use it.
    2. **Secondary** — curated CSV mapping (by ``accession`` → ``stem`` → ``gene``).
       The CSV never overrides a valid organism in the file; it is only used when
       step 1 yields nothing.
    3. **Optional fallback** — NCBI lookup by accession (if enabled).

    Parameters
    ----------
    record : SeqRecord
        GenBank record.
    file_stem : str
        File stem used to match curated mapping.
    mapping_csv : Path, optional
        Path to CSV with curated mappings; columns: ``stem``, ``donor``
        (optional: ``accession``, ``gene``).
    enable_ncbi_fallback : bool, default False
        If ``True``, query NCBI by accession when donor is unknown.
    ncbi_email : str, optional
        Required by NCBI; only used if fallback is enabled.
    ncbi_api_key : str, optional
        Optional NCBI API key.
    ncbi_cache : Path, optional
        JSON cache file for NCBI responses.

    Returns
    -------
    str or None
        Donor string, or ``None`` if it cannot be determined.
    """
    # 1) from record
    donor = _donor_from_record(record)
    if donor:
        return donor

    # 2) curated mapping
    mapping: dict[str, str] = {}
    if mapping_csv and Path(mapping_csv).is_file():
        mapping = _load_mapping_csv(Path(mapping_csv))

    gene_from_features: Optional[str] = None
    for feat in getattr(record, "features", []):
        if str(getattr(feat, "type", "")).lower() == "cds":
            q = getattr(feat, "qualifiers", {}) or {}
            gene_from_features = _first_qualifier(q, "gene", "label", "product")
            break

    acc = _parse_accession(record)
    donor = _mapping_lookup(mapping, file_stem, gene_from_features, acc)
    if donor:
        return donor

    # 3) NCBI fallback (optional)
    if enable_ncbi_fallback and acc:
        donor_ncbi = _ncbi_lookup_organism(
            acc, email=ncbi_email, api_key=ncbi_api_key, cache_path=ncbi_cache
        )
        donor = _clean_text(donor_ncbi)
        if donor:
            return donor

    return None


def _detect_vector_type(record: SeqRecord) -> str:
    """Detect backbone/antibiotic marker from feature qualifiers (best-effort).

    Parameters
    ----------
    record : SeqRecord
        GenBank record.

    Returns
    -------
    str
        A human-readable backbone label, e.g. ``"DVA (Addgene CIDAR MoClo, Amp)"``,
        ``"DVK (Addgene CIDAR MoClo, Kan)"`` or ``"Unbekannt"``.
    """
    haystack: list[str] = []
    for feat in getattr(record, "features", []):
        q = getattr(feat, "qualifiers", {}) or {}
        for key in ("note", "label", "gene", "product"):
            vals = q.get(key) or []
            if isinstance(vals, list):
                haystack.extend(str(v) for v in vals)

    s = " ".join(haystack).lower()
    if any(tok in s for tok in ("kanamycin", "kanr", "aph", "neo")):
        return "DVK (Addgene CIDAR MoClo, Kan)"
    if any(tok in s for tok in ("ampicillin", "ampr", "bla", "beta-lactamase")):
        return "DVA (Addgene CIDAR MoClo, Amp)"
    return "Unbekannt"


def _infer_parts_from_record(
    record: SeqRecord,
) -> tuple[Optional[str], Optional[str], Optional[str]]:
    """Infer Promoter, RBS and Gene from GenBank features (best-effort).

    Parameters
    ----------
    record : SeqRecord
        GenBank record.

    Returns
    -------
    tuple[str | None, str | None, str | None]
        ``(promoter, rbs, gene)`` best-effort inference.
    """
    promoter: Optional[str] = None
    rbs: Optional[str] = None
    gene: Optional[str] = None

    for feat in getattr(record, "features", []):
        ftype = str(getattr(feat, "type", "")).lower()
        q = getattr(feat, "qualifiers", {}) or {}

        # Promoter
        if promoter is None and (
            ftype == "promoter" or ("promoter" in (q.get("note") or [""])[0].lower())
        ):
            promoter = _first_qualifier(q, "label", "gene", "note")

        # RBS
        if rbs is None and ftype in {"rbs", "ribosome_binding_site", "misc_binding"}:
            cand = _first_qualifier(q, "label", "note")
            if cand and any(tag in cand.lower() for tag in ("rbs", "b00")):
                rbs = cand

        # Gene (prefer CDS)
        if ftype == "cds" and gene is None:
            gene = _first_qualifier(q, "gene", "label", "product")

    return promoter, rbs, gene


def _parse_parts_from_filename(
    stem: str,
) -> tuple[Optional[str], Optional[str], Optional[str]]:
    """Infer Promoter/RBS/Gene from a file name stem (heuristics).

    Parameters
    ----------
    stem : str
        File stem (e.g., ``'J23107_B0034_E0040'``).

    Returns
    -------
    tuple[str | None, str | None, str | None]
        ``(promoter, rbs, gene)`` best-effort guess from tokens.
    """
    tokens = [tok for chunk in stem.split("_") for tok in chunk.split("-")]
    promoter = next((t for t in tokens if t.upper().startswith("J23")), None)
    rbs = next((t for t in tokens if t.upper().startswith("B00")), None)
    gene = next(
        (t for t in tokens if any(k in t.lower() for k in ("pand", "adc"))), None
    )
    return promoter, rbs, gene


def build_s1_documentation(  # noqa: PLR0913 - explicit params make the API clearer
    folder_path: str | Path,
    *,
    output_name: str = "S1_Dokumentation.xlsx",
    recipients: str = "E. coli BL21, E. coli Top10, E. coli DH5alpha",
    default_donor: str = "C. glutamicum",
    rg_donor: int = 1,
    rg_recipient: int = 1,
    rg_construct: int = 1,
    prefer_features: bool = True,
    include_glob: Optional[str] = None,
    date_fmt: str = "%d.%m.%Y",
    # donor resolution knobs:
    donor_mapping_csv: Optional[Path] = None,
    enable_ncbi_fallback: bool = False,
    ncbi_email: Optional[str] = None,
    ncbi_api_key: Optional[str] = None,
    ncbi_cache: Optional[Path] = None,
) -> Path:
    """Build an S1 documentation Excel from GenBank files.

    Parameters
    ----------
    folder_path : str or Path
        Directory containing ``.gb`` / ``.gbk`` files.
    output_name : str, default "S1_Dokumentation.xlsx"
        Output filename written to the **current working directory**.
    recipients : str, default "E. coli BL21, E. coli Top10, E. coli DH5alpha"
        Target strains (comma-separated text for the “Empfänger” column).
    default_donor : str, default "C. glutamicum"
        Final fallback if no donor can be resolved.
    rg_donor : int, default 1
        Risk group for donor (“RG_Spender”).
    rg_recipient : int, default 1
        Risk group for recipient (“RG_Empfänger”).
    rg_construct : int, default 1
        Overall RG for the construct (“RG”).
    prefer_features : bool, default True
        If ``True``, extract Promoter/RBS/Gene from **features** first; fall
        back to filename heuristics if missing. If ``False``, use filename only.
    include_glob : str or None, optional
        If given, only process files matching this glob (e.g. ``"*TU1*.gb*"``).
    date_fmt : str, default "%d.%m.%Y"
        Date format used for “Erzeugt am”.
    donor_mapping_csv : Path, optional
        Curated mapping CSV (columns: ``stem``, ``donor``; optional:
        ``accession``, ``gene``). Used **only** if the GenBank record does not
        contain a usable organism.
    enable_ncbi_fallback : bool, default False
        If ``True``, try NCBI by accession *only if* neither record nor mapping
        provide a donor. Requires internet and ``ncbi_email``; uses a JSON cache
        if ``ncbi_cache`` is provided.
    ncbi_email, ncbi_api_key, ncbi_cache :
        Parameters forwarded to the NCBI fallback.

    Returns
    -------
    Path
        Absolute path of the written Excel file.

    Notes
    -----
    - Requires ``biopython`` and ``openpyxl`` (via ``pandas.to_excel``).
    - Columns written:
      ``["Nr.", "Spender", "RG_Spender", "Empfänger", "RG_Empfänger",
         "Ausgangsvektor", "Gen/Promotor/RBS", "Gefährdungspotential",
         "Bezeichnung", "RG", "Zulassung", "Erzeugt am", "Entsorgt am",
         "Unterschrift"]``.
    """
    src = Path(folder_path)
    if not src.is_dir():
        raise FileNotFoundError(f"Folder not found: {src}")

    files = sorted([p for p in src.iterdir() if p.suffix.lower() in {".gb", ".gbk"}])
    if include_glob:
        from fnmatch import fnmatch  # local import keeps top-level clean

        files = [p for p in files if fnmatch(p.name, include_glob)]

    today = time.strftime(date_fmt)  # same effect as datetime.today().strftime
    rows: list[dict[str, Any]] = []

    for idx, gb_path in enumerate(files, start=1):
        try:
            from Bio import SeqIO  # local import to avoid heavy top-level cost

            record = SeqIO.read(str(gb_path), "genbank")
        except Exception:  # pragma: no cover - tolerant loop over file set
            # skip unreadable files silently; log upstream if needed
            continue

        # --- parts (gene/promoter/RBS) ---
        prom_f: Optional[str] = None
        rbs_f: Optional[str] = None
        gene_f: Optional[str] = None
        if prefer_features:
            prom_f, rbs_f, gene_f = _infer_parts_from_record(record)

        prom_n, rbs_n, gene_n = _parse_parts_from_filename(gb_path.stem)

        promoter = prom_f or prom_n or "Unknown"
        rbs = rbs_f or rbs_n or "Unknown"
        gene = gene_f or gene_n or "Unknown"

        # --- donor resolution (primary → secondary → optional NCBI) ---
        donor = (
            resolve_donor(
                record,
                file_stem=gb_path.stem,
                mapping_csv=donor_mapping_csv,
                enable_ncbi_fallback=enable_ncbi_fallback,
                ncbi_email=ncbi_email,
                ncbi_api_key=ncbi_api_key,
                ncbi_cache=ncbi_cache,
            )
            or default_donor
        )

        vector = _detect_vector_type(record)

        rows.append(
            {
                "Nr.": idx,
                "Spender": donor,
                "RG_Spender": rg_donor,
                "Empfänger": recipients,
                "RG_Empfänger": rg_recipient,
                "Ausgangsvektor": vector,
                "Gen/Promotor/RBS": f"Gen: {gene}, Promotor: {promoter}, RBS: {rbs}",
                "Gefährdungspotential": "S1",
                "Bezeichnung": gb_path.stem,
                "RG": rg_construct,
                "Zulassung": "",
                "Erzeugt am": today,
                "Entsorgt am": "",
                "Unterschrift": "",
            }
        )

    df = pd.DataFrame(rows)
    out_path = Path.cwd() / output_name
    df.to_excel(out_path, index=False)  # engine=openpyxl (auto)
    return out_path
